// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Battery {
  final int level;
  final double voltage;
  final double current;
  final bool isCharging;

  const Battery({
    required this.level,
    required this.voltage,
    required this.current,
    required this.isCharging,
  });

  @override
  int get hashCode =>
      level.hashCode ^
      voltage.hashCode ^
      current.hashCode ^
      isCharging.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Battery &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          voltage == other.voltage &&
          current == other.current &&
          isCharging == other.isCharging;
}
