// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class StorageModel {
  final BigInt total;
  final BigInt used;

  const StorageModel({required this.total, required this.used});

  @override
  int get hashCode => total.hashCode ^ used.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageModel &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          used == other.used;
}
