// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ZramModel {
  final double origin;
  final double compressed;
  final double total;
  final double ratio;

  const ZramModel({
    required this.origin,
    required this.compressed,
    required this.total,
    required this.ratio,
  });

  @override
  int get hashCode =>
      origin.hashCode ^ compressed.hashCode ^ total.hashCode ^ ratio.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZramModel &&
          runtimeType == other.runtimeType &&
          origin == other.origin &&
          compressed == other.compressed &&
          total == other.total &&
          ratio == other.ratio;
}
