// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/battery.dart';
import '../models/ram.dart';
import '../models/storage.dart';
import '../models/zram.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Battery> getBatteryInfo() =>
    RustLib.instance.api.crateApiSimpleGetBatteryInfo();

Future<double> getBatteryTemperature() =>
    RustLib.instance.api.crateApiSimpleGetBatteryTemperature();

Future<void> setWifiThrottle({required bool enable}) =>
    RustLib.instance.api.crateApiSimpleSetWifiThrottle(enable: enable);

Future<double> getCpuTemperature() =>
    RustLib.instance.api.crateApiSimpleGetCpuTemperature();

Future<Float64List> getCpuFrequencies() =>
    RustLib.instance.api.crateApiSimpleGetCpuFrequencies();

Future<String> getCpuGovernor() =>
    RustLib.instance.api.crateApiSimpleGetCpuGovernor();

Future<void> setGovernor({required String governor}) =>
    RustLib.instance.api.crateApiSimpleSetGovernor(governor: governor);

Future<Ram> getRamInfo() => RustLib.instance.api.crateApiSimpleGetRamInfo();

Future<Zram> getSwapInfo() => RustLib.instance.api.crateApiSimpleGetSwapInfo();

Future<int> getSwappiness() =>
    RustLib.instance.api.crateApiSimpleGetSwappiness();

Future<void> setSwappiness({required int choice}) =>
    RustLib.instance.api.crateApiSimpleSetSwappiness(choice: choice);

Future<int> getVmDirtyRatio() =>
    RustLib.instance.api.crateApiSimpleGetVmDirtyRatio();

Future<void> setVmDirtyRatio({required int choice}) =>
    RustLib.instance.api.crateApiSimpleSetVmDirtyRatio(choice: choice);

Future<int> getVmDirtyBackgroundRatio() =>
    RustLib.instance.api.crateApiSimpleGetVmDirtyBackgroundRatio();

Future<void> setVmBackgroundDirtyRatio({required int choice}) => RustLib
    .instance
    .api
    .crateApiSimpleSetVmBackgroundDirtyRatio(choice: choice);

Future<Storage> getStorage() => RustLib.instance.api.crateApiSimpleGetStorage();

Future<void> writeFstrim() => RustLib.instance.api.crateApiSimpleWriteFstrim();

Future<void> writeClearLogs() =>
    RustLib.instance.api.crateApiSimpleWriteClearLogs();

Future<void> writeClearTempFiles() =>
    RustLib.instance.api.crateApiSimpleWriteClearTempFiles();

Future<void> writeLmkProfile({required int choice}) =>
    RustLib.instance.api.crateApiSimpleWriteLmkProfile(choice: choice);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Cow < 'static , str >>>
abstract class CowStr implements RustOpaqueInterface {}
