// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/battery_model.dart';
import '../models/ram_model.dart';
import '../models/zram_model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

BatteryModel getBatteryInfo() =>
    RustLib.instance.api.crateApiSimpleGetBatteryInfo();

double getCpuTemperature() =>
    RustLib.instance.api.crateApiSimpleGetCpuTemperature();

Float64List getCpuFrequencies() =>
    RustLib.instance.api.crateApiSimpleGetCpuFrequencies();

RamModel getRamInfo() => RustLib.instance.api.crateApiSimpleGetRamInfo();

ZramModel getSwapInfo() => RustLib.instance.api.crateApiSimpleGetSwapInfo();
