// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/battery_model.dart';
import '../models/ram_model.dart';
import '../models/zram_model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<BatteryModel> getBatteryInfo() =>
    RustLib.instance.api.crateApiSimpleGetBatteryInfo();

Future<double> getBatteryTemperature() =>
    RustLib.instance.api.crateApiSimpleGetBatteryTemperature();

Future<double> getCpuTemperature() =>
    RustLib.instance.api.crateApiSimpleGetCpuTemperature();

Future<Float64List> getCpuFrequencies() =>
    RustLib.instance.api.crateApiSimpleGetCpuFrequencies();

Future<String> getCpuGovernor() =>
    RustLib.instance.api.crateApiSimpleGetCpuGovernor();

Future<void> setGovernor({required String governor}) =>
    RustLib.instance.api.crateApiSimpleSetGovernor(governor: governor);

Future<RamModel> getRamInfo() =>
    RustLib.instance.api.crateApiSimpleGetRamInfo();

Future<ZramModel> getSwapInfo() =>
    RustLib.instance.api.crateApiSimpleGetSwapInfo();

Future<String> getSwappiness() =>
    RustLib.instance.api.crateApiSimpleGetSwappiness();

Future<void> setSwappiness({required int choice}) =>
    RustLib.instance.api.crateApiSimpleSetSwappiness(choice: choice);
